#!/usr/bin/env -S docker stack deploy --with-registry-auth nginx -c

version: "3.9"

# NOTE deploy
# docker stack deploy --with-registry-auth -c docker-stack.yaml nginx
# docker node update --label-add nginx=true <NODE-NAME>
# docker service update --label-add nginx.http.server-name=www.example.com <SERVICE-NAME>

services:
  nginx:
    image: ghcr.io/zerocluster/nginx
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role == manager"
          - "node.labels.nginx == true"

    # healthcheck:
    #   test: curl -f http://127.0.0.1/api/check-health || exit 1
    #   start_period: 60s
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

    environment:
      NODE_ENV: production

    command: ""

    networks: [main]

    ports:
      - { published: 80, target: 80, mode: host }
      # - { published: 5432, target: 5432, mode: host }
      # - { published: 8085, target: 8085, mode: host }

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }
      - { type: bind, source: /var/run/docker.sock, target: /var/run/docker.sock }
      - { type: volume, source: nginx, target: /var/local/package/data }

    build:
      context: .

networks:
  main: { external: true }

volumes:
  nginx: { name: nginx }

x-build:
  default_tag: latest
  auto_tags: [main, latest, next]
