version: "3.9"

x-build_default_tag: latest
x-build_tags_mapping: { main: latest }
x-build_auto_tags: [main, devel, latest]

networks:
  private: { external: true }

services:
  test:
    image: softvisio/nginx
    init: true
    shm_size: 1g

    build:
      x-images: ["registry.myworkforce.com/nginx/nginx"]

    ports:
      - { published: 80, target: 80 }
      - { published: 443, target: 443 }

    environment:
      LOADBALANCER_NETWORK: private

    networks: [private]

    stop_grace_period: 5m

    deploy:
      replicas: 1

      restart_policy:
        condition: on-failure

    placement:
      max_replicas_per_node: 1
      constraints:
        - "node.role == manager"
        - "node.labels.loadbalancer"
