#!/usr/bin/env -S docker stack deploy --with-registry-auth nginx -c

version: "3.9"

# NOTE deploy
# docker stack deploy --with-registry-auth -c docker-stack.yaml nginx
# docker node update --label-add nginx=true <NODE-NAME>
# docker service update --label-add nginx.server-name=www.example.com <SERVICE-NAME>

services:
  nginx:
    image: softvisio/nginx
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role == manager"
          - "node.labels.nginx == true"

    networks: [private]

    ports:
      - { published: 80, target: 80 }
      - { published: 443, target: 443 }

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }
      - { type: bind, source: /var/run/docker.sock, target: /var/run/docker.sock }
      - { type: volume, source: nginx, target: /var/lib/nginx }

    build:
      context: .

networks:
  private: { external: true }

volumes:
  nginx: { name: nginx }

x-build:
  default_tag: latest
  # autobuild_tags: [main, devel, latest, next]
