#!/usr/bin/env -S docker stack deploy --with-registry-auth nginx -c

version: "3.9"

# NOTE deploy
# docker stack deploy --with-registry-auth -c docker-stack.yaml nginx
# docker node update --label-add nginx=true <NODE-NAME>
# docker service update --label-add nginx.http.server-name=www.example.com <SERVICE-NAME>

services:
  nginx:
    image: ghcr.io/zerocluster/nginx
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role == manager"
          - "node.labels.nginx == true"

    command: ""

    networks: [main]

    ports:
      - { published: 80, target: 8080, mode: host }

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }
      - { type: bind, source: /var/run/docker.sock, target: /var/run/docker.sock }
      - { type: volume, source: nginx, target: /var/local/package/data }

    build: .

networks:
  main: { external: true }

volumes:
  nginx: { name: nginx }
